import React from "react";
import Head from "next/head";
import Header from "./Header";
import Footer from "./footer";
import styles from "../styles/Layout.module.css";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Cricket App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header className={styles.header} />
      <main className={styles.container}>{children}</main>
      <Footer className={styles.footer} />
    </div>
  );
};

export default Layout;
